version: '3.4'

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana:8.5.21
    networks:
      - grafana
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./datasources:/etc/grafana/provisioning/datasources
      # - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml