{
 "title": "API Monitoring",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "HOST:",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "90th 95th 99th responses time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "90th {{method}} {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "95th {{method}} {{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "99th {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Number of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count[1m]))"
    }
   ]
  },
  {
   "title": "Number of failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"4.*\"}[1m]))"
    }
   ]
  }
 ]
}