{
 "title": "API General Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "90th 95th 99th responses time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "90th {{method}} {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "95th {{method}} {{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "99th {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Requests details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"2.*\"}[1m])) by (route, method)",
     "legendFormat": "2xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"4.*\"}[1m])) by (route, method)",
     "legendFormat": "4xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"5.*\"}[1m])) by (route, method)",
     "legendFormat": "5xx {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Number of 200 OK vs Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"2.*\"}[1m]))",
     "legendFormat": "Valid requests"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code!~\"2.*\"}[1m]))",
     "legendFormat": "Error requests"
    }
   ]
  },
  {
   "title": "Number of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count[1m]))",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}