version: '3.4'

networks:
  k6:
  grafana-external:
    name: grafana_grafana
    external: true

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana-external
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ../../k6-scripts:/scripts
